language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=django111
        - python: 3.7
          env: TOXENV=django21-py37

install:
  - pip install tox
  - pip install coverage
  - pip install coveralls

script: tox

after_success:
- coveralls