language: python
python:
    - "2.7"
env:
  - TOXENV=django17
  - TOXENV=django18
install: 
  - pip install tox
  - pip install coverage
  - pip install coveralls
script: tox
after_success:
  - coveralls
